* WAIT AI中屏研发评估
SCHEDULED: <2025-12-22 Mon>

#+begin_quote
建议：相关工作都交由椰壳来完成
#+end_quote

驱动由椰壳实现
蓝牙音响功能，作为device设备，工作量可能略多一些
摄像头前置2m手动遮挡？如何实现？还是保护盖

扬声器MIC阵列回声消除

SDK更新


双屏设置(内置屏和hdmi)


AI智能体对接

语音引擎

语音遥控器谁家的





摄像头相关

物理按键

* DONE 梯慧眼云平台APP接口与联通DMP平台接口差异
CLOSED: [2025-12-29 Mon 08:47] SCHEDULED: <2025-12-22 Mon>

我们云平台仿造阿里规范标准实现。

所以，与联通 DMP 的还是有挺大差异的。

* KILL 重庆广电 NGB-J接口可行性
CLOSED: [2025-12-29 Mon 09:04] SCHEDULED: <2025-12-22 Mon>

#+begin_quote
已经否定，跟新光确认歌华也没有使用 NGB-J 接口，塞科调用的是qin 接口。

跟重庆沟通他们会整理之前 mstar 项目使用的 porting 接口由我们来实现。

#+end_quote

找国科确认NGB-J接口完整性以及DVB相关功能支持情况

自己android版本评估NGB-J稳定性

* DONE 移动集采移动框架中含有终端管理应用模块 STBManager (与tr069不同，海思空实现)
CLOSED: [2025-12-29 Mon 09:05] SCHEDULED: <2025-12-22 Mon>

这个不是 TR069 而是框架里面终端管理应用的， amlogic 平台代码中有实现逻辑

* TODO 山东语音在播放界面识别阶段存在无法显示的问题
SCHEDULED: <2025-12-29 Mon>

1 播放情况下基本必现，例如本地播放等
2 茁壮平台无问题，但是本地播放一样存在问题
3 dumpsys SurfaceFlinger  以及HWC
4 screenrecord/screencap
5 新版app放到310板子上没问题，旧版app放到320上也可以显示(与语音)

6 logcat surfaceflinger  hwc


hwc HI_FB -   HI_GFBG

ro.config.gfx2d_compress


dumpsys 
Surfaceflinger window activity



在语音没有提示情况下，通过input keyevent KEYCODE_VOLUNE_DOWN调出音量条，就可以看到都立马显示出来了


* TODO 媒体服务器 wvp+zlmediakit
SCHEDULED: <2025-12-29 Mon>

https://github.com/648540858/wvp-GB28181-pro


https://gitee.com/pan648540858/wvp-GB28181-pro


https://github.com/ZLMediaKit/ZLMediaKit


https://mp.weixin.qq.com/s/wJJtFu9Kp9N70I4LEXBOJQ


https://mp.weixin.qq.com/s/sdJk8Aj56iIwODXvmcqvyQ


ABLMediaServer 可以替代 ZLMediaKit；文档更详细，更容易入手；
ry-wvp 可以替代wvp


流媒体我只推荐mediamtx

https://github.com/bluenviron/mediamtx




https://mp.weixin.qq.com/s/vRMoV2ePbIfZvm5wOGRr2g





https://mp.weixin.qq.com/s/4bqtmF242efDcbAPchuZEQ


一个RK3588方案

https://wiki.t-firefly.com/zh_CN/iCore-3588JQ/linux_compile.html


firefly aibox 方案

https://www.t-firefly.com/wiki

* DONE tunnelto tailscale cloudflared
CLOSED: [2025-12-29 Mon 08:53] SCHEDULED: <2025-12-29 Mon>

https://github.com/agrinman/tunnelto

tunnelto 应该并不怎么样，

* TODO rk3588 ffmpeg 硬解 zlmediakit部署
SCHEDULED: <2026-01-05 Mon>

mvp or ruyi vue pro

